auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: salamanderrex.github.io/
url: http://salamanderrex.github.io/
feed: /atom.xml
author_info: <a href="http://salamanderrex.github.io/">QingYu</a>
