auto: true

markdown: kramdown
rouge : true
paginate: 8
permalink: /:title

title: salamanderrex.github.io/
url: http://salamanderrex.github.io/
feed: /atom.xml
author_info: <a href="http://salamanderrex.github.io/">QingYu</a>
